name: ci/cd pipeline to deploy to tomcat
on: 
  push:
    branches: master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: set-up jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'   
      - name: validate with maven
        run: mvn validate
      - name: compile with maven
        run: mvn compile
      - name: test with maven
        run: mvn test
      - name: package with maven
        run: mvn package
      - name: verify WAR file
        run: ls -lh target/
      
      - name: Build, Test and SonarQube Scan
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=Train-Book-resevation \
            -Dsonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Test Nexus Authentication
        env:
          NEXUS_SERVER_URL: ${{ secrets.NEXUS_SERVER_URL }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          echo "Testing authentication to Nexus at $NEXUS_SERVER_URL"
          RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
            --head \
            "$NEXUS_SERVER_URL")

          echo "HTTP response code: $RESPONSE_CODE"

          if [[ "$RESPONSE_CODE" -eq 200 ]]; then
            echo "Authentication successful."
            exit 0
          else
            echo "Authentication failed."
            exit 1
          fi
      - name: Upload WAR to Nexus (Manual Method)
        env:
          NEXUS_SERVER_URL: ${{ secrets.NEXUS_SERVER_URL }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
         echo "Uploading WAR to Nexus..."
         curl -v -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
         --upload-file ./target/TrainBook-1.0.0-SNAPSHOT.war "${NEXUS_SERVER_URL}"/repository/train-ticket/

      - name: Download WAR from Nexus
        run: |
          echo "Downloading artifact from Nexus..."
          wget "$NEXUS_DOWNLOAD"

      - name: Deploy to Tomcat
        run: |
         curl -v -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} \
         -T target/TrainBook-1.0.0-SNAPSHOT.war \
         "http://${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/TrainBook-1.0.0-SNAPSHOT.war&update=true"


